# SPDX-FileCopyrightText: (c) 2026 Joel Winarske
# SPDX-License-Identifier: MIT
# GenShaderBlob.cmake — turn a set of .spv files into one C++ header of uint32_t arrays.
# Driven by EmbedShaders.cmake. Args (cmake -D...):
#   OUT   = output header path
#   SPV   = '|'-separated list of .spv files
#   NAMES = '|'-separated list of symbol bases (parallel to SPV)

string(REPLACE "|" ";" spv_list "${SPV}")
string(REPLACE "|" ";" name_list "${NAMES}")

set(body "// Generated by GenShaderBlob.cmake — do not edit.\n#pragma once\n#include <cstdint>\n\n")

list(LENGTH spv_list n)
math(EXPR last "${n} - 1")
foreach(i RANGE ${last})
  list(GET spv_list ${i} spv)
  list(GET name_list ${i} sym)

  file(READ "${spv}" hex HEX)
  string(LENGTH "${hex}" hexlen)
  math(EXPR words "${hexlen} / 8")

  # SPIR-V is little-endian uint32 words; reassemble byte-swapped.
  string(APPEND body "static const uint32_t ${sym}_spv[] = {\n")
  set(line "  ")
  math(EXPR wlast "${words} - 1")
  foreach(w RANGE ${wlast})
    math(EXPR off "${w} * 8")
    string(SUBSTRING "${hex}" ${off} 8 b)   # b0 b1 b2 b3 (byte order in file)
    string(SUBSTRING "${b}" 0 2 b0)
    string(SUBSTRING "${b}" 2 2 b1)
    string(SUBSTRING "${b}" 4 2 b2)
    string(SUBSTRING "${b}" 6 2 b3)
    string(APPEND line "0x${b3}${b2}${b1}${b0},")
    string(LENGTH "${line}" ll)
    if(ll GREATER 88)
      string(APPEND body "${line}\n")
      set(line "  ")
    else()
      string(APPEND line " ")
    endif()
  endforeach()
  if(NOT line STREQUAL "  ")
    string(APPEND body "${line}\n")
  endif()
  string(APPEND body "};\n")
  string(APPEND body "static const uint32_t ${sym}_spv_count = ${words};\n\n")
endforeach()

get_filename_component(outdir "${OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${outdir}")
file(WRITE "${OUT}" "${body}")
message(STATUS "wrote ${OUT} (${n} shader blob(s))")
